// Generated by transclude. Do not edit. `npm run check` rewrites it.
//
// Every type here was produced by TypeScript from the file it describes.

export {};

// Declared by the compiler. Every context type below names these.
type __Cookies = {
  get(name: string): string | undefined;
  all(): Record<string, string>;
  set(name: string, value: string, options?: __CookieOptions): void;
  delete(name: string, options?: __CookieOptions): void;
  signed: {
    get(name: string): Promise<string | undefined>;
    all(): Promise<Record<string, string>>;
    set(name: string, value: string, options?: __CookieOptions): Promise<void>
  }
};
type __Shape<T> = {
  [K in keyof T]: T[K] extends never[] ? any[] : T[K]
};
type __CookieOptions = {
  path?: string;
  domain?: string;
  maxAge?: number;
  expires?: Date;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: 'Strict' | 'Lax' | 'None'
};

// Declared by the app, in the file each was written in.
type Track = 'learn' | 'machine' | 'make' | 'play' | 'tech' | 'work' | 'world';
type Era = {
  slug: string;
  from: number;
  to: number;
  name: string;
  kicker: string;
  dek: string;
  body?: string | undefined;
  dark: boolean;
  texture: string;
  bg: string;
  ink: string;
  accent: string;
};
type Entry = {
  id: string;
  year: number;
  date?: string | undefined;
  until?: string | number | undefined;
  track: Track;
  title: string;
  dek?: string | undefined;
  where?: string | undefined;
  tags?: string[] | undefined;
  body?: string | undefined;
  spec?: {
    label: string;
    value: string;
  }[] | undefined;
  links?: {
    href: string;
    label: string;
  }[] | undefined;
  image?: Media | undefined;
  feature?: boolean | undefined;
  draft?: boolean | undefined;
  needs?: string | undefined;
};
type Media = {
  src: string;
  alt: string;
  width: number;
  height: number;
  caption?: string | undefined;
};
type Project = {
  slug: string;
  name: string;
  dek: string;
  year: number;
  until?: number | undefined;
  role?: string | undefined;
  stack?: string[] | undefined;
  links?: {
    href: string;
    label: string;
  }[] | undefined;
  body?: string | undefined;
  facts?: {
    label: string;
    value: string;
  }[] | undefined;
  image?: Media | undefined;
  draft?: boolean | undefined;
  needs?: string | undefined;
};

/** Properties of `<link-row>`, from its <script element> block. */
export type LinkRowProps = {
  links: any[];
  label: string;
};

/** Properties of `<media-figure>`, from its <script element> block. */
export type MediaFigureProps = {
  src: string;
  alt: string;
  width: number;
  height: number;
  caption: string;
};

/** Properties of `<org-mark>`, from its <script element> block. */
export type OrgMarkProps = {
  logo: string;
  initials: string;
};

/** Properties of `<spec-list>`, from its <script element> block. */
export type SpecListProps = {
  rows: any[];
  label: string;
};

/** Properties of `<svg-icon>`, from its <script element> block. */
export type SvgIconProps = {
  library: string;
  name: string;
  label: string;
};

/** Properties of `<time-entry>`, from its <script element> block. */
export type TimeEntryProps = {
  href: string;
  stamp: string;
  track: string;
  trackLabel: string;
  heading: string;
  dek: string;
  tags: any[];
  mine: boolean;
  feature: boolean;
  needs: string;
  vt: string;
};

/** The `ctx` argument of `root/_layout.html`'s loader. */
export type RootLayoutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {};
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `root/_layout.html`. */
export type RootLayoutData = {
  site: {
    name: string;
    domain: string;
    origin: string;
    role: string;
    tagline: string;
    intro: string;
    seeking: string;
    email: string;
    phone: string;
    location: string;
    elsewhere: {
      label: string;
      href: string;
    }[];
    inProgress: boolean;
  };
  nav: {
    href: string;
    label: string;
    hint: string;
    current: string | boolean;
  }[];
  canonical: string;
  unwritten: number;
  built: number;
};

/** The `ctx` argument of `about`'s <script server> loader. */
export type AboutContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `about`'s <script server> block. */
export type AboutData = {
  site: {
    name: string;
    domain: string;
    origin: string;
    role: string;
    tagline: string;
    intro: string;
    seeking: string;
    email: string;
    phone: string;
    location: string;
    elsewhere: {
      label: string;
      href: string;
    }[];
    inProgress: boolean;
  };
  eras: number;
  entries: number;
  written: number;
  years: number;
  from: number;
  to: number;
  tracks: {
    id: Track;
    label: string;
    blurb: string;
    count: number;
    swatch: string;
  }[];
  layers: string;
  ownLayers: string;
  otherLayers: string;
  tags: {
    tag: string;
    count: number;
    href: string;
  }[];
};

/** The `ctx` argument of `backstage`'s <script server> loader. */
export type BackstageContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `backstage`'s <script server> block. */
export type BackstageData = {
  entries: {
    id: string;
    year: number;
    title: string;
    needs: string;
    file: string;
    href: string;
  }[];
  roles: {
    id: string;
    title: string;
    needs: string;
  }[];
  projects: {
    slug: string;
    name: string;
    needs: string;
  }[];
  count: number;
};

/** The `ctx` argument of `colophon`'s <script server> loader. */
export type ColophonContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `colophon`'s <script server> block. */
export type ColophonData = {
  entries: number;
  written: number;
  eras: number;
};

/** The `ctx` argument of `projects-index`'s <script server> loader. */
export type ProjectsIndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `projects-index`'s <script server> block. */
export type ProjectsIndexData = {
  projects: {
    slug: string;
    name: string;
    dek: string;
    when: string;
    role: string;
    stack: string[];
  }[];
};

/** The `ctx` argument of `work`'s <script server> loader. */
export type WorkContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `work`'s <script server> block. */
export type WorkData = {
  site: {
    name: string;
    domain: string;
    origin: string;
    role: string;
    tagline: string;
    intro: string;
    seeking: string;
    email: string;
    phone: string;
    location: string;
    elsewhere: {
      label: string;
      href: string;
    }[];
    inProgress: boolean;
  };
  capabilities: {
    group: string;
    note: string;
    items: string[];
  }[];
  toolchain: {
    decade: string;
    items: string[];
  }[];
  also: {
    label: string;
    items: {
      what: string;
      where: string;
      when: string;
      href?: string | undefined;
    }[];
  }[];
  roles: {
    id: string;
    title: string;
    org: string;
    url?: string | undefined;
    where: string;
    from: string;
    to: string;
    summary?: string | undefined;
    brand?: string | undefined;
    draft?: boolean | undefined;
    needs?: string | undefined;
    when: string;
    did: string[];
    stack: string[];
    mark: {
      label: string;
      initials: string;
      logo: string;
    };
  }[];
};

/** The `ctx` argument of `index`'s <script server> loader. */
export type IndexContext = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `index`'s <script server> block. */
export type IndexData = {
  site: {
    name: string;
    domain: string;
    origin: string;
    role: string;
    tagline: string;
    intro: string;
    seeking: string;
    email: string;
    phone: string;
    location: string;
    elsewhere: {
      label: string;
      href: string;
    }[];
    inProgress: boolean;
  };
  query: {
    tag: string;
    track: string;
    label: string;
    active: boolean;
  };
  filters: {
    id: string;
    label: string;
    count: number;
    href: string;
    current: string | false;
    swatch: string;
  }[];
  allCurrent: string | boolean;
  noteTail: string;
  found: number;
  total: number;
  chapters: {
    era: Era;
    previous: string;
    count: number;
    years: {
      year: number;
      entries: {
        id: string;
        href: string;
        stamp: string;
        track: Track;
        trackLabel: string;
        title: string;
        dek: string;
        tags: {
          label: string;
          href: string;
        }[];
        mine: boolean;
        feature: boolean;
        needs: string;
        vt: string;
      }[];
    }[];
    style: string;
  }[];
  contents: {
    slug: string;
    name: string;
    kicker: string;
    from: number;
    to: number;
    count: number;
    countLabel: string;
    accent: string;
  }[];
  bars: string;
  spanText: string;
};

/** Route params for `/era/:slug`. */
export type EraSlugParams = { slug: string };

/** The `ctx` argument of `era-_slug`'s <script server> loader. */
export type EraSlugContext = {
  url: string;
  params: {
    slug: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `era-_slug`'s <script server> block. */
export type EraSlugData = __Shape<{
  found: boolean;
  era: null;
  years: never[];
  others: never[];
  style: string;
  span: string;
  dark: boolean;
  texture: string;
}> | __Shape<{
  found: boolean;
  era: Era;
  years: {
    year: number;
    entries: {
      id: string;
      href: string;
      stamp: string;
      track: Track;
      trackLabel: string;
      title: string;
      dek: string;
      tags: {
        label: string;
        href: string;
      }[];
      mine: boolean;
      feature: boolean;
      needs: string;
      vt: string;
    }[];
  }[];
  others: {
    slug: string;
    name: string;
    span: string;
    current: string | boolean;
  }[];
  style: string;
  dark: boolean;
  texture: string;
  span: string;
}>;

/** Route params for `/log/:id`. */
export type LogIdParams = { id: string };

/** The `ctx` argument of `log-_id`'s <script server> loader. */
export type LogIdContext = {
  url: string;
  params: {
    id: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `log-_id`'s <script server> block. */
export type LogIdData = __Shape<{
  found: boolean;
  entry: null;
  card: null;
  era: null;
  track: string;
  style: string;
  dark: boolean;
  vt: string;
  previous: null;
  next: null;
}> | __Shape<{
  found: boolean;
  entry: Entry;
  card: {
    id: string;
    href: string;
    stamp: string;
    track: Track;
    trackLabel: string;
    title: string;
    dek: string;
    tags: {
      label: string;
      href: string;
    }[];
    mine: boolean;
    feature: boolean;
    needs: string;
    vt: string;
  };
  era: Era;
  track: string;
  style: string;
  dark: boolean;
  vt: string;
  previous: {
    href: string;
    title: any;
    year: any;
  } | null;
  next: {
    href: string;
    title: any;
    year: any;
  } | null;
}>;

/** Route params for `/projects/:slug`. */
export type ProjectsSlugParams = { slug: string };

/** The `ctx` argument of `projects-_slug`'s <script server> loader. */
export type ProjectsSlugContext = {
  url: string;
  params: {
    slug: string
  };
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `projects-_slug`'s <script server> block. */
export type ProjectsSlugData = __Shape<{
  found: boolean;
  project: null;
  when: string;
}> | __Shape<{
  found: boolean;
  project: Project;
  when: string;
}>;

/** The `ctx` argument of `404`'s <script server> loader. */
export type _404Context = {
  url: string;
  params: {};
  route: {
    id: string;
    pattern: string;
    path: string
  };
  layout: {
    site: {
      name: string;
      domain: string;
      origin: string;
      role: string;
      tagline: string;
      intro: string;
      seeking: string;
      email: string;
      phone: string;
      location: string;
      elsewhere: {
        label: string;
        href: string;
      }[];
      inProgress: boolean;
    };
    nav: {
      href: string;
      label: string;
      hint: string;
      current: string | boolean;
    }[];
    canonical: string;
    unwritten: number;
    built: number;
  };
  request: Request | null;
  fragment: string | null;
  action: unknown;
  response: {
    status: number;
    headers: Headers
  };
  cookies: __Cookies;
  absolute: (path: string) => string;
  revalidateTag: (tag: string) => void;
  after: (work: Promise<unknown>) => void
};

/** Data returned by `404`'s <script server> block. */
export type _404Data = {
  eras: Era[];
};

declare global {
  interface HTMLElementTagNameMap {
    "link-row": HTMLElement;
    "media-figure": HTMLElement;
    "org-mark": HTMLElement;
    "spec-list": HTMLElement;
    "svg-icon": HTMLElement;
    "time-entry": HTMLElement;
  }
}
