"""Rebuild app/data/covers/tachyons.js from the markup in app/data/covers/*.js.

The twelve covers on /log/book-covers are 2017 markup and carry nothing but
Tachyons class names. This pulls the rules those class names need out of the
stylesheet the old site loaded whole, which is vendored beside this file so the
page does not depend on a checkout of that site being on disk.

Run it after changing a class in any cover, or the class will have no rule:

    python3 scripts/build-cover-css.py

Two things happen to the rules on the way out, and nothing else:

1. The three breakpoint blocks are flattened in source order, so `-ns`, `-m` and
   `-l` always apply. A cover is not a page and has no viewport of its own; it
   should look the way it looked on a wide screen in 2017 however narrow the
   column it lands in.

2. Every rem and px becomes a share of a 768px cover, in `cqi`. `.covers__art`
   is a container, so a cover scales with its column and the type keeps its
   proportion to the artwork.
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
COVERS = ROOT / 'app/data/covers'
SOURCES = [ROOT / 'scripts/tachyons/tachyons.min.css', ROOT / 'scripts/tachyons/site.css']
OUT = COVERS / 'tachyons.js'

# The width the covers were drawn against: the old site's `mw7-ns` article.
DESIGN = 768.0

RULE = re.compile(r'@media[^{]+\{(?:[^{}]*\{[^{}]*\})*\}|[^{}]+\{[^{}]*\}', re.S)
LENGTH = re.compile(r'(-?\d*\.?\d+)(rem|px)\b')


def classes_used():
    """Every class name on an element inside a cover's `art`."""
    found = set()
    for path in sorted(COVERS.glob('*.js')):
        if path.name == 'tachyons.js':
            continue
        source = path.read_text(encoding='utf-8')
        art = source.split('  art: `', 1)[1] if '  art: `' in source else ''
        for attr in re.finditer(r'class="([^"]+)"', art):
            found.update(attr.group(1).split())
    return found


def subset(css, used):
    """The rules whose selector names one of those classes, media blocks flattened."""
    patterns = [re.compile(r'\.' + re.escape(name) + r'(?![\w-])') for name in used]

    def wanted(selector):
        return any(p.search(selector) for p in patterns)

    kept = []
    for rule in RULE.findall(css):
        if rule.lstrip().startswith('@media'):
            inner = rule[rule.index('{') + 1:rule.rindex('}')]
            kept += [r for r in re.findall(r'[^{}]+\{[^{}]*\}', inner, re.S) if wanted(r[:r.index('{')])]
        elif wanted(rule[:rule.index('{')]):
            kept.append(rule)
    return ''.join(kept)


def to_container_units(css):
    def convert(match):
        value = float(match.group(1))
        pixels = value * 16 if match.group(2) == 'rem' else value
        share = pixels * 100 / DESIGN
        return f'{share:.4f}'.rstrip('0').rstrip('.') + 'cqi'

    return LENGTH.sub(convert, css)


used = classes_used()
css = to_container_units(''.join(subset(path.read_text(encoding='utf-8'), used) for path in SOURCES))

header = f"""// Generated by scripts/build-cover-css.py. Do not edit by hand: change a class
// in a cover and run that script again, or the class will have no rule.
//
// The Tachyons rules the twelve covers use, and only those: {len(used)} classes, which
// was the entire vocabulary the covers had. The three breakpoint blocks are
// flattened so a cover always gets the wide-screen tier it was drawn for, and
// every rem and px is a share of a {DESIGN:.0f}px cover in `cqi`, so the cover scales
// with its column rather than with the window.
//
// It lives here rather than in `app/styles/` because one page needs it, and the
// entry writes it into its own `<style>` behind an `@scope`, so a class as blunt
// as `.tc` cannot reach anything that is not a cover.

export const tachyons = `"""

body = css.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
OUT.write_text(header + '\n' + body + '\n`;\n', encoding='utf-8')
print(f'  {OUT.relative_to(ROOT)}: {len(used)} classes, {len(body)} bytes')
